export enum EnvsConsts {
  TELEGRAM_MESSAGE_TEMPLATE = 'TELEGRAM_MESSAGE_TEMPLATE',
  USER_NAME_REGEXP = 'USER_NAME_REGEXP',

  ADDITIONAL_SILENCE_TIME = 'ADDITIONAL_SILENCE_TIME',

  COUCHDB_STATUSES_URL_PREFIX = 'COUCHDB_STATUSES_URL_PREFIX',
  COUCHDB_STATUSES_DB_USER = 'COUCHDB_STATUSES_DB_USER',
  COUCHDB_STATUSES_DB_PASSWORD = 'COUCHDB_STATUSES_DB_PASSWORD',

  COUCHDB_STATUS_RULES_URL_PREFIX = 'COUCHDB_STATUS_RULES_URL_PREFIX',
  COUCHDB_STATUS_RULES_DB_USER = 'COUCHDB_STATUS_RULES_DB_USER',
  COUCHDB_STATUS_RULES_DB_PASSWORD = 'COUCHDB_STATUS_RULES_DB_PASSWORD',

  COUCHDB_USERS_URL_PREFIX = 'COUCHDB_USERS_URL_PREFIX',
  COUCHDB_USERS_DB_USER = 'COUCHDB_USERS_DB_USER',
  COUCHDB_USERS_DB_PASSWORD = 'COUCHDB_USERS_DB_PASSWORD',

  COUCHDB_REDMINE_CHANGES_PARAMS_URL_PREFIX = 'COUCHDB_REDMINE_CHANGES_PARAMS_URL_PREFIX',
  COUCHDB_REDMINE_CHANGES_PARAMS_DB_USER = 'COUCHDB_REDMINE_CHANGES_PARAMS_DB_USER',
  COUCHDB_REDMINE_CHANGES_PARAMS_DB_PASSWORD = 'COUCHDB_REDMINE_CHANGES_PARAMS_DB_PASSWORD',

  COUCHDB_REDMINE_CHANGES_URL_PREFIX = 'COUCHDB_REDMINE_CHANGES_URL_PREFIX',
  COUCHDB_REDMINE_CHANGES_DB_USER = 'COUCHDB_REDMINE_CHANGES_DB_USER',
  COUCHDB_REDMINE_CHANGES_DB_PASSWORD = 'COUCHDB_REDMINE_CHANGES_DB_PASSWORD',

  COUCHDB_REDMINE_ISSUES_URL_PREFIX = 'COUCHDB_REDMINE_ISSUES_URL_PREFIX',
  COUCHDB_REDMINE_ISSUES_DB_USER = 'COUCHDB_REDMINE_ISSUES_DB_USER',
  COUCHDB_REDMINE_ISSUES_DB_PASSWORD = 'COUCHDB_REDMINE_ISSUES_DB_PASSWORD',

  NEW_ISSUE_STATUS = 'NEW_ISSUE_STATUS',

  CLOSED_STATUES_FOR_WEEKLY_REPORT = 'CLOSED_STATUES_FOR_WEEKLY_REPORT',
}