export enum EnvsConsts {
  TELEGRAM_MESSAGE_TEMPLATE = 'TELEGRAM_MESSAGE_TEMPLATE',
  USER_NAME_REGEXP = 'USER_NAME_REGEXP',

  COUCHDB_STATUSES_URL_PREFIX = 'COUCHDB_STATUSES_URL_PREFIX',
  COUCHDB_STATUSES_DB_USER = 'COUCHDB_STATUSES_DB_USER',
  COUCHDB_STATUSES_DB_PASSWORD = 'COUCHDB_STATUSES_DB_PASSWORD',

  COUCHDB_STATUS_RULES_URL_PREFIX = 'COUCHDB_STATUS_RULES_URL_PREFIX',
  COUCHDB_STATUS_RULES_DB_USER = 'COUCHDB_STATUS_RULES_DB_USER',
  COUCHDB_STATUS_RULES_DB_PASSWORD = 'COUCHDB_STATUS_RULES_DB_PASSWORD',

  COUCHDB_USERS_URL_PREFIX = 'COUCHDB_USERS_URL_PREFIX',
  COUCHDB_USERS_DB_USER = 'COUCHDB_USERS_DB_USER',
  COUCHDB_USERS_DB_PASSWORD = 'COUCHDB_USERS_DB_PASSWORD',
}